DataDecipher.WebApp/Models/ParsedData.cs
using System.Data;

namespace DataDecipher.WebApp.Models
{
    // You may need to install the Microsoft.AspNetCore.Http.Abstractions package into your project
    public class ParsedData
    {
        public string fileName { get; set; }
        public string filePath { get; set; }
        public string parsedData { get; set; }
        public DataTable parsedDataTable { get; set; }
        public string[] records { get; set; }
        public string parsedDataAsJson { get; set; }
    }
}

DataDecipher.WebApp/Models/RawData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;

namespace DataDecipher.WebApp.Models
{
    // You may need to install the Microsoft.AspNetCore.Http.Abstractions package into your project
    public class RawData
    {
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string RawDataContent { get; set; }
    }
}

DataDecipher.WebApp/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using System.Data;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using DataDecipher.WebApp.Models;
using DataDecipher.WebApp.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.File;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using RestSharp;
using Newtonsoft.Json.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DataDecipher.WebApp.Controllers
{
    public class MainController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> user;
        private readonly IConfiguration _configuration;


        public MainController(ApplicationDbContext ctx, UserManager<ApplicationUser> usr, IConfiguration cfg)
        {
            _context = ctx;
            user = usr;
            _configuration = cfg;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => user.GetUserAsync(HttpContext.User);

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            MainViewModel main = new MainViewModel();

            var sharedMethods = _context.SharedMethods.Where(x => x.UserId == GetCurrentUserAsync().Result.Id);
            string sharedMethodsIds = String.Join(',', sharedMethods.Select(x => x.MethodId).ToArray());
            var methodList = await _context.Methods.Include(y => y.SharedUsers).Include(y => y.CreatedBy).Where(x => x.CreatedBy.Id == GetCurrentUserAsync().Result.Id || sharedMethodsIds.Contains(x.Id)).ToListAsync();
            main.AvailableMethods = methodList;

            return View(main);
        }

        [HttpPost]
        public async Task<ActionResult> SelectMethod(MainViewModel main)
        {
            main.SelectedMethod = _context.Methods.Include(y => y.LinkedDataSources).Where(x => x.Id == main.SelectedMethod.Id).First();

            if (main.SelectedMethod.LinkedDataSources.Count == 0)
            {
                var plan = _context.Organizations.Where(y => y.Id == GetCurrentUserAsync().Result.OrganizationId).Select(z => z.SelectedPlanId);
                var connectors = _context.PlanDataConnectors.Where(y => y.PlanId == plan.First()).Select(z => z.DataSourceConnectorId);
                var connectorIds = String.Join(',', connectors.ToArray());
                ViewBag.AvailableDataConnectors = _context.DataSourceConnectors.Where(y => connectorIds.Contains(y.Id)).ToList();

                main.AvailableDataSources = await _context.DataSources.Include(x => x.CreatedBy).Include(y => y.Type).Where(z => connectorIds.Contains(z.TypeId) && z.CreatedById == GetCurrentUserAsync().Result.Id).ToListAsync();
                main.AvailableSampleDataSources = await _context.SampleDataSources.Include(x => x.CreatedBy).Include(y => y.Type).Where(z => connectorIds.Contains(z.TypeId) && z.CreatedById == GetCurrentUserAsync().Result.Id).ToListAsync();

                main.SelectedDataSource = new DataSource();
            }
            else
            {
                main.SelectedDataSource = _context.MethodDataSources.Include(y => y.Datafile).Where(x => x.Id == main.SelectedMethod.LinkedDataSources.First().Id).Select(z => z.Datafile).First();
                main.SelectedDataSourceName = main.SelectedDataSource.Uri;
            }

            return PartialView("_SetDataSource", main);

        }

        [HttpPost]
        public async Task<IActionResult> CreateNewMethod(Models.Method method)
        {
            if (ModelState.IsValid)
            {
                method.CreatedBy = GetCurrentUserAsync().Result;
                method.CreatedDate = System.DateTime.Now;
                method.LastModifiedDate = System.DateTime.Now;
                method.Status = "Draft";
                _context.Methods.Add(method);
                await _context.SaveChangesAsync();
            }

            MainViewModel main = new MainViewModel();
            main.SelectedMethod = method;

            var plan = _context.Organizations.Where(y => y.Id == GetCurrentUserAsync().Result.OrganizationId).Select(z => z.SelectedPlanId);
            var connectors = _context.PlanDataConnectors.Where(y => y.PlanId == plan.First()).Select(z => z.DataSourceConnectorId);
            var connectorIds = String.Join(',', connectors.ToArray());
            ViewBag.AvailableDataConnectors = _context.DataSourceConnectors.Where(y => connectorIds.Contains(y.Id)).ToList();

            main.AvailableDataSources = await _context.DataSources.Include(x => x.CreatedBy).Include(y => y.Type).Where(z => connectorIds.Contains(z.TypeId) && z.CreatedById == GetCurrentUserAsync().Result.Id).ToListAsync();
            main.AvailableSampleDataSources = await _context.SampleDataSources.Include(x => x.CreatedBy).Include(y => y.Type).Where(z => connectorIds.Contains(z.TypeId) && z.CreatedById == GetCurrentUserAsync().Result.Id).ToListAsync();

            main.SelectedDataSource = new DataSource();
            main.SelectedMethod.LinkedDataSources = new List<MethodDataSource>();

            return PartialView("_SetDataSource", main);
        }

        [HttpPost]
        public ActionResult ShowSelectedMethodDetails(MainViewModel main, string SelectedMethodId)
        {
            main.SelectedMethod = _context.Methods.Where(method => method.Id == SelectedMethodId).First();
            return PartialView("~/Views/Methods/_DisplaySelectedMethod.cshtml", main);
        }

        [HttpPost]
        public async Task<ActionResult> SelectDataSource(MainViewModel main)
        {
            try
            {

                string fileName = main.SelectedDataSourceName.Split('/').Last();

                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(_configuration.GetConnectionString("StorageConnectionString"));

                // Create a CloudFileClient object for credentialed access to Azure Files.
                CloudFileClient fileClient = storageAccount.CreateCloudFileClient();

                // Get a reference to the file share we created previously.
                CloudFileShare cloudFileShare = fileClient.GetShareReference(GetCurrentUserAsync().Result.Id);

                await cloudFileShare.CreateIfNotExistsAsync();

                CloudFileDirectory cloudFileDirectory = cloudFileShare.GetRootDirectoryReference();

                CloudFile cloudFile = cloudFileDirectory.GetFileReference(fileName);

                MemoryStream stream = new MemoryStream();

                await cloudFile.DownloadToStreamAsync(stream);

                stream.Position = 0;

                StreamReader reader = new StreamReader(stream);

                main.RawData = reader.ReadToEnd();

                //Copied raw data to processed data in case user skips the pre-processing/cleansing step
                main.ProcessedData = main.RawData;

                return PartialView("_DisplayDataSource", main);
            }
            catch(Exception e)
            {
                return PartialView("_GeneralError",e);
            }

        }

        [HttpPost]
        public async Task<ActionResult> SelectSampleDataSource(MainViewModel main)
        {
            main.SelectedDataSourceName = main.SelectedSampleDataSourceName;

            string fileName = main.SelectedDataSourceName.Split('/').Last();

            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(_configuration.GetConnectionString("StorageConnectionString"));

            // Create a CloudFileClient object for credentialed access to Azure Files.
            CloudFileClient fileClient = storageAccount.CreateCloudFileClient();

            // Get a reference to the file share we created previously.
            CloudFileShare cloudFileShare = fileClient.GetShareReference("samples");

            await cloudFileShare.CreateIfNotExistsAsync();

            CloudFileDirectory cloudFileDirectory = cloudFileShare.GetRootDirectoryReference();

            CloudFile cloudFile = cloudFileDirectory.GetFileReference(fileName);

            MemoryStream stream = new MemoryStream();

            await cloudFile.DownloadToStreamAsync(stream);

            stream.Position = 0;

            StreamReader reader = new StreamReader(stream);

            main.RawData = reader.ReadToEnd();

            //Copied raw data to processed data in case user skips the pre-processing/cleansing step
            main.ProcessedData = main.RawData;

            return PartialView("_DisplayDataSource", main);
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewDataSource(MainViewModel main, IFormFile DataFile)
        {
            DataSource dataSource = main.SelectedDataSource;
            dataSource.DataFile = DataFile;

            if (dataSource == null ||
                dataSource.DataFile == null || dataSource.DataFile.Length == 0)
                return Content("file not selected");

            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(_configuration.GetConnectionString("StorageConnectionString"));

            // Create a CloudFileClient object for credentialed access to Azure Files.
            CloudFileClient fileClient = storageAccount.CreateCloudFileClient();

            // Get a reference to the file share we created previously.
            CloudFileShare cloudFileShare = fileClient.GetShareReference(GetCurrentUserAsync().Result.Id);
            await cloudFileShare.CreateIfNotExistsAsync();

            CloudFileDirectory cloudFileDirectory = cloudFileShare.GetRootDirectoryReference();


            CloudFile cloudFile = cloudFileDirectory.GetFileReference(dataSource.DataFile.FileName);
            await cloudFile.DeleteIfExistsAsync();

DataDecipher.WebApp/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataDecipher.WebApp.Data;
using DataDecipher.WebApp.Models;

namespace DataDecipher.WebApp.Controllers
{
    public class PlanController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlanController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Plan
        public async Task<IActionResult> Index()
        {

            return View(await _context.Plans.Include( i => i.EnabledDataConnectors).ThenInclude((i => i.DataSourceConnector)).Include(e => e.Organizations).ToListAsync());
        }

        // GET: Plan/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Plan plan = await _context.Plans.Include(i => i.EnabledDataConnectors).ThenInclude((i => i.DataSourceConnector)).Include(e => e.Organizations)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // GET: Plan/Create
        public IActionResult Create()
        {
            
            Plan pass = new Plan();
            pass.AvailableDataConnectors = _context.DataSourceConnectors.ToList();
            return View(pass);
        }

        // POST: Plan/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Plan plan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(plan);
                foreach (DataSourceConnector i in plan.AvailableDataConnectors.Where(t=>t.IsSelected==true))
                {
                    _context.Add(new PlanDataConnector() { PlanId = plan.Id, DataSourceConnectorId = i.Id });
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }

        // GET: Plan/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans.FindAsync(id);
            if (plan == null)
            {
                return NotFound();
            }

            List<PlanDataConnector> linkedDS = _context.PlanDataConnectors.Where(x=> x.PlanId == id ).ToList();
            if(linkedDS != null)
            {
                plan.AvailableDataConnectors = _context.DataSourceConnectors.Select(dc => new DataSourceConnector()
                { Id = dc.Id, Name = dc.Name, Extension = dc.Extension, IsSelected = linkedDS.Any(x=>x.DataSourceConnectorId == dc.Id)}).ToList();

            }
            return View(plan);
        }

        // POST: Plan/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,TrialPeriod,Price,AvailableDataConnectors")] Plan plan)
        {
            if (id != plan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plan);
                    List<PlanDataConnector> linkedDS = _context.PlanDataConnectors.Where(x => x.PlanId == id).ToList();
                    if (linkedDS != null)
                    {
                        foreach(var item in linkedDS)
                            _context.Remove(item);

                    }
                    foreach (DataSourceConnector i in plan.AvailableDataConnectors.Where(t => t.IsSelected == true))
                    {
                        _context.Add(new PlanDataConnector() { PlanId = plan.Id, DataSourceConnectorId = i.Id });
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanExists(plan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }

        // GET: Plan/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans.Include(i => i.EnabledDataConnectors).ThenInclude((i => i.DataSourceConnector)).Include(e => e.Organizations)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // POST: Plan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var plan = await _context.Plans.FindAsync(id);
            _context.Plans.Remove(plan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanExists(string id)
        {
            return _context.Plans.Any(e => e.Id == id);
        }
    }
}

DataDecipher.WebApp/Views/Shared/_GeneralError.cshtml
@model System.Exception
<div class="row>">
    <div class="col-md-12">
        <h6>Oops something went wrong</h6>
        <br />
    </div>
</div>
<div class="card-deck">
    <div class="card">
        <div class="card-header">
            <span class="text-primary">Report error</span>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label class="badge badge-default-noborder">Error details</label>
                <textarea readonly asp-for="@Model.Message" class="form-control" rows="5">@Model.Message</textarea>
            </div>

            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Mail us" />
            </div>

        </div>
    </div>
</div>

DataDecipher.WebApp/Views/Shared/_HeaderNavBar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<DataDecipher.WebApp.Data.ApplicationUser> SignInManager
@inject UserManager<DataDecipher.WebApp.Data.ApplicationUser> UserManager
@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post" id="logoutForm">
        <nav class="navbar navbar-expand-lg bg-primary fixed-top" >
            <div class="container-fluid">
                <div class="dropdown button-dropdown">
                    <a id="menu-toggle" href="#menu-toggle" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                        <span class="button-bar"></span>
                        <span class="button-bar"></span>
                        <span class="button-bar"></span>
                    </a>
                </div>
                <div class="navbar-translate">
                    <a class="navbar-brand" data-placement="bottom" target="_blank">
                        Welcome @UserManager.GetUserName(User)
                    </a>
                    <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                </div>
               <ul class="navbar-nav">
                    <li class="nav-item">
                        <button type="submit" class="btn btn-primary">Logout</button>
                    </li>
                </ul>
                
            </div>
        </nav>
    </form>

}
else
{
  
    <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" data-placement="bottom" target="_blank">
                    Data Decipher
                </a>
                <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">
                        Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">
                        <p>Login</p>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
   
 }

DataDecipher.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>@ViewData["Title"] - DataDecipher</title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/now-ui-kit.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/simple-sidebar.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/jquery.dataTables.min.css" />

</head>

<body class="login-page sidebar-collapse">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/assets/js/now-ui-kit.js"></script>
    @RenderSection("Scripts", required: false)

    @await Html.PartialAsync("_HeaderNavBar")
    <div class="page-header">
        <div class="page-header-image" style="background-image: url(../../lib/bootstrap/assets/img/main-background.jpg)"></div>
        @RenderBody()
        <footer class="footer">
            <div class="container">
                <div class="copyright">
                    &copy; DataDecipher
                    <script>document.write(new Date().getFullYear())</script>
                </div>
            </div>
        </footer>
    </div>


</body>
</html>

DataDecipher.WebApp/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>@ViewData["Title"] - DataDecipher</title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/now-ui-kit.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/simple-sidebar.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/assets/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/Visualization.css">
</head>
<body class="profile-page sidebar-collapse">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/jQuery-ajax-unobtrusive-master/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jQuery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/assets/js/now-ui-kit.js"></script>
    <script src="~/lib/bootstrap/assets/js/quill.min.js"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="~/js/visualization.js"></script>

    @RenderSection("Scripts", required: false)
    @await Html.PartialAsync("_HeaderNavBar")
    <div id="wrapper" class="Wrapper">
        @await Html.PartialAsync("~/Views/Shared/_SideBar.cshtml")
        <div class="section">
            @RenderBody()
        </div>
    </div>

    <script>
$("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
});</script>
    <script>
$(document).ready(function() {
            $('#myTable').dataTable();
});</script>

</body>
</html>

DataDecipher.WebApp/Views/Shared/_RawData.cshtml
@model DataDecipher.WebApp.Models.RawData
<div class="row>">
    <div class="col-md-12">
        <h6>3. Display selected file</h6>
        <br />
    </div>
</div>
<div class="card-deck">
    <div class="card">
        <div class="card-header">
            <span class="text-primary">Contents of the file: @Model.FileName</span>
        </div>
        <div class="card-body">
        <p>
            @Model.RawDataContent
        </p>
        </div>
    </div> 
</div>

DataDecipher.WebApp/Views/Shared/_SideBar.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                Data Decipher
            </a>
        </li>
        <li class="sidebar-brand">
            Main functions
        </li>
        <li class="active">
            <a asp-controller="Main" asp-action="Index">Home</a>
        </li>
        <li>
            <a asp-controller="Methods" asp-action="Index">Method</a>
        </li>
        @if ((await AuthorizationService.AuthorizeAsync(User, "RequireDDAdminRole")).Succeeded || (await AuthorizationService.AuthorizeAsync(User, "RequireSuperUserRole")).Succeeded)
        {
            <li>
                <a asp-controller="DataSources" asp-action="Index">Data Source</a>
            </li>
            <li>
                <a asp-controller="DataProcessingRules" asp-action="Index">Processing Rules</a>
            </li>
            <li>
                <a href="#" onclick="ToggleParserCollapse()">Parser</a>
                <ul id="collapseParsers" style="list-style: none; display:none;">
                    <li>
                        <a asp-controller="CsvParserConfig" asp-action="Index">Delimited File</a>
                    </li>
                    <li>
                        <a asp-controller="XmlParserConfig" asp-action="Index">XML File</a>
                    </li>
                    <li>
                        <a asp-controller="TxtParserConfig" asp-action="Index">TXT File</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#" onclick="TogglePublishCollapse()">Publish</a>
                <ul id="collapsePublish" style="list-style: none; display:none;">
                    <li>
                        <a asp-controller="ConfigureFileServer" asp-action="Index">File Server</a>
                    </li>
                    <li>
                        <a asp-controller="ConfigureMSSqlServer" asp-action="Index">MSSQL Server</a>
                    </li>
                </ul>
            </li>
        }
        @if ((await AuthorizationService.AuthorizeAsync(User, "RequireDDAdminRole")).Succeeded)
        {
            <li class="sidebar-brand">
                Administrator functions
            </li>
            <li>
                <a asp-controller="DataSourceConnectors" asp-action="Index">Data Connectors</a>
            </li>
            <li>
                <a asp-controller="Plan" asp-action="Index">Plan</a>
            </li>
            <li>
                <a asp-controller="Organization" asp-action="Index">Organization</a>
            </li>
            <li>
                <a asp-controller="ApplicationRoles" asp-action="Index">Application Roles</a>
            </li>
            <li>
                <a asp-controller="ApplicationUser" asp-action="Index">Application Users</a>
            </li>
            <li>
                <a asp-controller="SampleDataSources" asp-action="Index">Sample Datasets</a>
            </li>
        }
    </ul>
</div>

<script>

    function ToggleParserCollapse() {
      var x = document.getElementById('collapseParsers');
      if (x.style.display == 'block') {
        x.style.display = 'none';
      } else {
        x.style.display = 'block';
      }
    }

    function TogglePublishCollapse() {
      var x = document.getElementById('collapsePublish');
      if (x.style.display == 'block') {
        x.style.display = 'none';
      } else {
        x.style.display = 'block';
      }
    }

</script>